{{ $secrets := .Values.sync.secrets.secrets }}
{{ $project_id := .Values.sync.secrets.project_id}}
{{- if gt (len $secrets) 0 -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-sync-{{ include "sample.name" . }}
spec:
  provider: gcp
  parameters:
    auth: pod-adc
    secrets: |
    {{- range $secrets }}
      - resourceName: "projects/{{ $project_id }}/secrets/{{.}}/versions/latest"
        path: "{{.}}"
    {{- end }}
  secretObjects:
  {{- range $secrets }}
  - secretName: "{{.}}"
    type: Opaque
    data: 
    - objectName: "{{.}}"
      key: value
  {{- end }}
{{- end }}